<../../mkconfig

DIRS=\
	venti\

TARG=\
        ventry.dis\
        vcache.dis\
        vtest.dis\
        ventisrv.dis\

MODULES=\

SYSMODULES=\
	arg.m\
	bufio.m\
	daytime.m\
	dial.m\
	draw.m\
	keyring.m\
	string.m\
	sys.m\
	vac.m\
	venti.m\

DISBIN=$ROOT/dis

<$ROOT/mkfiles/mkdis
<$ROOT/mkfiles/mksubdirs
